# ==========================================
# DRIVE → NOTION → MCP SYNC UTILITY
# Grand Slam Option C | Phase 1
# Auto-generated by Create-DriveToNotionMCP.ps1
# ==========================================

$DriveFolderID   = "1Umy_4CUB6pV7gLQFE5zUoP0cq_OQicX6"
$NotionBuildsDB  = "2385cd1fe0a2806181b0f5c31c018ecb"
$NotionRecoveryDB = "24b5cd1fe0a2806aa572f3aac32a6342"
$MCP_Endpoint    = "https://mcp.zapier.com/api/mcp/mcp"

$GoogleAPIToken  = $env:GOOGLE_API_TOKEN
$NotionToken     = $env:NOTION_TOKEN

function Send-MCPUpdate($Payload) {
    try {
        $json = $Payload | ConvertTo-Json -Depth 5
        Invoke-RestMethod -Uri $MCP_Endpoint -Method POST -Body $json -ContentType "application/json"
        Write-Host "[OK] MCP endpoint notified." -ForegroundColor Green
    } catch {
        Write-Host "[ERR] Failed to notify MCP endpoint: $_" -ForegroundColor Red
    }
}

function Get-DriveFiles {
    Write-Host "[INFO] Pulling files from Google Drive folder..." -ForegroundColor Cyan
    $DriveAPI = "https://www.googleapis.com/drive/v3/files?q='$DriveFolderID'+in+parents&fields=files(id,name,mimeType,modifiedTime)"
    try {
        $response = Invoke-RestMethod -Uri $DriveAPI -Headers @{ Authorization = "Bearer $GoogleAPIToken" }
        return $response.files
    } catch {
        Write-Host "[ERR] Drive fetch failed: $_" -ForegroundColor Red
        return @()
    }
}

function Push-ToNotion($File) {
    $payload = @{
        parent = @{ database_id = $NotionBuildsDB }
        properties = @{
            Name = @{ title = @(@{ text = @{ content = $File.name } }) }
            FileID = @{ rich_text = @(@{ text = @{ content = $File.id } }) }
            Type = @{ select = @{ name = $File.mimeType } }
            Modified = @{ date = @{ start = $File.modifiedTime } }
        }
    }
    try {
        Invoke-RestMethod -Uri "https://api.notion.com/v1/pages" `
            -Method POST `
            -Headers @{
                "Authorization" = "Bearer $NotionToken"
                "Content-Type" = "application/json"
                "Notion-Version" = "2022-06-28"
            } `
            -Body ($payload | ConvertTo-Json -Depth 5)
        Write-Host "[OK] Sent to Notion Builds DB: $($File.name)" -ForegroundColor Green
    } catch {
        Write-Host "[ERR] Notion upload failed for $($File.name): $_" -ForegroundColor Red
    }
}

Write-Host "====================================="
Write-Host "   DRIVE → NOTION → MCP SYNC START   "
Write-Host "====================================="

$Files = Get-DriveFiles
if ($Files.Count -eq 0) {
    Write-Host "[INFO] No new files found in Drive folder."
    exit
}

foreach ($File in $Files) {
    Push-ToNotion $File

    $Payload = @{
        action = "SYNC_COMPLETE"
        fileName = $File.name
        fileID = $File.id
        mimeType = $File.mimeType
        modified = $File.modifiedTime
        notionTarget = $NotionBuildsDB
        timestamp = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
    }
    Send-MCPUpdate $Payload
}

Write-Host "====================================="
Write-Host "   SYNC COMPLETE                     "
Write-Host "====================================="
